### ISSUE TITLE
Left/right scrolling

### ISSUE THREAD

**Issue by acemac** [BHP-DevHub/react-timeline-9000#113]
Do you guys have a roadmap of features you want to add? Or are there plans for adding left/right scrolling?

I've been doing work to improve performance on react-calendar-timeline, but you guys have already solved the problem of many thousands of items in potentially hundreds of groups.  

We're currently at a crossroads of whether it will be less effort to change our current implementation to meet performance, or do we port across to this and add the features it is missing.

**Comment by vasdee** [comment]
We don't have a current roadmap at the moment, but it is a very nice idea. 

There's no plans at the moment to add left or right scrolling, part of the reason why this library was created was because it felt like react-calendar-timeline was dictating too much how the component should function. One of our goals with this library is to put the interaction control back onto the developer and leaving the rendering work to the timeline.

We'd be happy to take on any suggestions/PRs that would help facilitate the left/right scrolling flow as long and also, for the record we just ported from react-calendar-timeline to this one and it was a solid week of work.

**Comment by lilfolr** [comment]
Closed due to inactivity
