### ISSUE TITLE
Should we just remove the yarn.lock file?

### ISSUE THREAD

**Issue by bendog** [BHP-DevHub/react-timeline-9000#191]
Since this is a package, should we just remove the yarn.lock file? 
In python world this wouldn't be included in a package codebase, and it only seems to get dependabot upset.

**Comment by lilfolr** [comment]
No.
yarn.lock ensures the developers who work on this package are running the exact same dependencies.
You running different minor versions to me is a recipe for disaster imo (especially in JS). 
Dependabot is complaining because we're using old, vulnerable libraries - the fix is updating, not ignoring 🙂

**Comment by bendog** [comment]
Seems legit. 
Should the package.json be updated with these version bumps too?

**Comment by lilfolr** [comment]
We probably should to keep things clean, but its not required for the version bumps.  
In general you would only upgrade `package.json`, and let yarn sort out `yarn.lock`.  

I don't think dependabot changed `package.json` because our `package.json` uses the `^` which allows for upgrading minor & patch versions - [eg](https://github.com/BHP-DevHub/react-timeline-9000/blob/master/package.json#L86). 
[See here](https://stackoverflow.com/a/22345808/3535990)

**Comment by bendog** [comment]
Yes, but should we be bumping the minimums versions?

**Comment by lilfolr** [comment]
Yeah, nothing wrong with staying up to date
